name: 10-controlling the execution flow
on:
   workflow_dispatch:
                   inputs:
                       pass-unit-tests:
                            type: boolean
                            default: false
jobs:
    lint-build:
        runs-on: ubuntu-latest
        steps:
            - name: "Lint and build"
              run: echo "Lint & building project"
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: "Running unit tests"
              run: echo "Running Tests"
        
            - name: "faling tests"
              run: exit 1
              if: ${{inputs.pass-unit-tests == false}}
    deploy-nonprod:
        runs-on: ubuntu-latest
        if: ${{needs.lint-build.result == 'success' && needs.unit-tests.result == 'success'}}
        steps:
            - name: "Deploying to nonprod"
              run: echo "Deploying to nonprod..."
              
    e2e-tests:
        runs-on: ubuntu-latest
        if : ${{needs.deploy-nonprod.result == 'success'}}
        steps:
            - name: "RUnning E2E tests"
              run: echo "Running e2e tests"
    deploy-prod:
        runs-on: ubuntu-latest
        if: ${{needs.e2e-tests.result == 'success' && needs.load-tests.result == 'success'}}
        steps:
            - name: "Deploying to prod"
              run: echo "Deploying to prod..."
    
    