name: 13-Caching
on:
    workflow_dispatch:
                    inputs:
                        use-cache:
                            description: "Weather to execute Cache step"
                            type: boolean
                            default: true
                        node-version:
                            description: "Choose any Node Version"
                            type: choice
                            options:
                                - 18.x
                                - 20.x
                                - 21.x
                            default: 20.x
jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
               working-directory: 13-caching/react-app
       
        # 1checout the code
        # 2. Install dependencies.
        # 3. Linting , formatting, unit testing, building etc.
        # 4. Depoy to nonprod enviornment.
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                   node-version: ${{inputs.node-version}}
            - name: Download Cache Dependencies
              uses: actions/cache@v3
              if: ${{inputs.use-cache}}
              id: cache
              with: 
                 path: 13-caching/react-app/node_modules
                 key: deps-node-modules-${{hashFiles('13-caching/react-app/package-lock.json')}}
            - name: Install Dependencies
              if: steps.cache.outputs.cache-hit != 'true'
              run: npm ci
              
            - name:  Testing
              run:  npm run test
             
            - name: building
              run: npm run build
     
            - name: Deploying to nonprod
              run: echo "Deploying to Non-Prod"

